-- Seed NEET-UG Biology topics, questions, and SEO pages.

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('endocrine-system-and-hormones', 'NEET-UG', 'Biology', 'Endocrine system and hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Endocrine system and hormones MCQs for NEET-UG Biology', 'Practice Endocrine system and hormones NEET-UG Biology questions with NCERT explanations.', 20, 1)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('dna-rna-replication-transcription-translation', 'NEET-UG', 'Biology', 'DNA RNA replication transcription translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'DNA RNA replication transcription translation MCQs for NEET-UG Biology', 'Practice DNA RNA replication transcription translation NEET-UG Biology questions with NCERT explanations.', 25, 2)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('cell-theory-and-cell-organelles', 'NEET-UG', 'Biology', 'Cell theory and cell organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Cell theory and cell organelles MCQs for NEET-UG Biology', 'Practice Cell theory and cell organelles NEET-UG Biology questions with NCERT explanations.', 22, 3)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('plant-respiration', 'NEET-UG', 'Biology', 'Plant respiration', 'plant-respiration', 'NCERT Biology Class 11, Chapter 12', 'Plant respiration MCQs for NEET-UG Biology', 'Practice Plant respiration NEET-UG Biology questions with NCERT explanations.', 7, 4)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('excretion-and-kidney-function', 'NEET-UG', 'Biology', 'Excretion and kidney function', 'excretion-and-kidney-function', 'NCERT Biology Class 11, Chapter 16', 'Excretion and kidney function MCQs for NEET-UG Biology', 'Practice Excretion and kidney function NEET-UG Biology questions with NCERT explanations.', 1, 5)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('neuron-nerve-impulse-synapse', 'NEET-UG', 'Biology', 'Neuron nerve impulse synapse', 'neuron-nerve-impulse-synapse', 'NCERT Biology Class 11, Chapter 18', 'Neuron nerve impulse synapse MCQs for NEET-UG Biology', 'Practice Neuron nerve impulse synapse NEET-UG Biology questions with NCERT explanations.', 1, 6)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('recombinant-dna-technology', 'NEET-UG', 'Biology', 'Recombinant DNA technology', 'recombinant-dna-technology', 'NCERT Biology Class 12, Chapter 9', 'Recombinant DNA technology MCQs for NEET-UG Biology', 'Practice Recombinant DNA technology NEET-UG Biology questions with NCERT explanations.', 1, 7)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('mutation-and-gene-expression', 'NEET-UG', 'Biology', 'Mutation and gene expression', 'mutation-and-gene-expression', 'NCERT Biology Class 12, Chapter 5', 'Mutation and gene expression MCQs for NEET-UG Biology', 'Practice Mutation and gene expression NEET-UG Biology questions with NCERT explanations.', 4, 8)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('pedigree-analysis-and-inheritance-patterns', 'NEET-UG', 'Biology', 'Pedigree analysis and inheritance patterns', 'pedigree-analysis-and-inheritance-patterns', 'NCERT Biology Class 12, Chapter 4', 'Pedigree analysis and inheritance patterns MCQs for NEET-UG Biology', 'Practice Pedigree analysis and inheritance patterns NEET-UG Biology questions with NCERT explanations.', 6, 9)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('human-reproductive-system-and-gametogenesis', 'NEET-UG', 'Biology', 'Human reproductive system and gametogenesis', 'human-reproductive-system-and-gametogenesis', 'NCERT Biology Class 12, Chapter 2', 'Human reproductive system and gametogenesis MCQs for NEET-UG Biology', 'Practice Human reproductive system and gametogenesis NEET-UG Biology questions with NCERT explanations.', 1, 10)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('basic-genetic-diseases-as-inheritance-examples', 'NEET-UG', 'Biology', 'Basic genetic diseases as inheritance examples', 'basic-genetic-diseases-as-inheritance-examples', 'NCERT Biology Class 12, Chapter 7', 'Basic genetic diseases as inheritance examples MCQs for NEET-UG Biology', 'Practice Basic genetic diseases as inheritance examples NEET-UG Biology questions with NCERT explanations.', 1, 11)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO topics (id, exam, subject, name, slug, ncert_ref, seo_title, seo_description, question_count, sort_order)
VALUES ('immunity-pathogens-vaccines', 'NEET-UG', 'Biology', 'Immunity pathogens vaccines', 'immunity-pathogens-vaccines', 'NCERT Biology Class 12, Chapter 7', 'Immunity pathogens vaccines MCQs for NEET-UG Biology', 'Practice Immunity pathogens vaccines NEET-UG Biology questions with NCERT explanations.', 1, 12)
ON CONFLICT (id) DO UPDATE SET question_count = EXCLUDED.question_count, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516662', 516662, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'The disease in children due to iodine deficiency or hypothyroidism during embryonic development is', 'Addison''s disease', 'Dwarfism', 'Acromegaly', 'Cretinism', 'D', 'Addison''s disease is due to adrenal cortex dysfunction. Dwarfism results from growth hormone deficiency or inadequate secretion. Acromegaly occurs due to excessive growth hormone in adults. Cretinism involves intellectual disability and developmental delay in children due to iodine deficiency or hypothyroidism during embryonic development.', 100, 98, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516664', 516664, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Long-term iodine deficiency in food can lead to', 'cretinism', 'acromegaly', 'goiter', 'rickets', 'C', 'Long-term iodine deficiency leads to insufficient synthesis of thyroid hormones, which results in feedback stimulation of the adenohypophysis to secrete more TSH, leading to thyroid hyperplasia and enlargement.', 100, 98, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520895', 520895, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'The chromosomal genome in eukaryotes is', 'linear double-stranded DNA molecule', 'circular double-stranded DNA molecule', 'linear single-stranded DNA molecule', 'linear single-stranded RNA molecule', 'A', 'The chromosomal genome in eukaryotes is typically linear and double-stranded, whereas prokaryotes often have a circular chromosome.', 100, 98, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520922', 520922, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'What is the role of RNA primer during DNA replication?', 'Provides a 3''OH end for dNTP addition', 'Extends Okazaki fragments', 'Participates in forming the primosome', 'Assists helicase action', 'A', 'The RNA primer provides a 3''OH end where DNA polymerase can add dNTPs during DNA replication.', 100, 98, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-521057', 521057, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which of the following statements about gene expression is incorrect?', 'Some genes express their products as proteins', 'Some genes express their products as RNA', 'Some genes undergo processes like transcription and translation', 'Always involves processes like transcription and translation', 'D', 'Gene expression does not always involve both transcription and translation. Some genes can be expressed through only the process of transcription, such as in the case of RNA genes.', 100, 98, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516220', 516220, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which of the following conditions can lead to an increase in Basal Metabolic Rate (BMR)?', 'renal syndrome', 'pathological fasting', 'adrenal cortex dysfunction', 'hyperthyroidism', 'D', 'In hyperthyroidism, BMR can be up to 25%-80% higher than normal. In the other conditions, BMR is generally lower.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516237', 516237, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which hormone has the greatest impact on body heat production?', 'noradrenaline', 'adrenaline', 'thyroid hormone', 'parathyroid hormone', 'C', 'Thyroid hormone plays a crucial role in regulating metabolic rate and heat production in the body.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516580', 516580, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which of the following hormones has a lipophilic characteristic?', 'growth hormone', 'insulin', 'aldosterone', 'adrenaline', 'C', 'Aldosterone is a steroid hormone, which is lipophilic and can easily pass through the cell membrane. Growth hormone, insulin, and adrenaline are mostly hydrophilic and require receptors on the cell surface for action.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516660', 516660, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'In a state of rest, the most important humoral factor regulating heat production in the human body is', 'thyroxine', 'adrenaline', 'noradrenaline', 'acetylcholine', 'A', 'Thyroxine, produced by the thyroid gland, plays a crucial role in regulating basal metabolic rate and heat production during rest. Adrenaline, noradrenaline, and acetylcholine are primarily involved in stress responses and other physiological functions but are not the most important humoral factors for heat production at rest.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516729', 516729, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'The secretion is regulated by the body''s fat storage and participates in weight regulation. Which hormone is involved?', 'leptin', 'thyroxine', 'adrenaline', 'insulin', 'A', 'Leptin, secreted by adipose tissue, regulates body weight by signaling to the brain about fat stores.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520377', 520377, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which technique does not involve nucleic acid hybridization?', 'protein blotting', 'gene chip', 'DNA blotting', 'PCR', 'A', 'Protein blotting involves the detection of proteins, whereas gene chip, DNA blotting, and PCR involve nucleic acid hybridization.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520569', 520569, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Respiratory chain in eukaryotic cells is present in', 'cytoplasm', 'nucleus', 'mitochondria', 'peroxisomes', 'C', 'The respiratory chain in eukaryotic cells is primarily located in the mitochondria.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520614', 520614, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which of the following hormones can inhibit fat mobilization and breakdown?', 'adrenaline', 'noradrenaline', 'insulin', 'glucagon', 'C', 'Insulin is known to inhibit lipolysis in adipose tissue, whereas adrenaline, noradrenaline, and glucagon promote fat mobilization.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520827', 520827, 'NEET-UG', 'Biology', 'plant-respiration', 'plant-respiration', 'NCERT Biology Class 11, Chapter 12', 'Which of the following pathways is most closely related to nucleic acid synthesis?', 'glycolysis', 'gluconeogenesis', 'urea cycle', 'pentose phosphate pathway', 'D', 'The pentose phosphate pathway produces ribose-5-phosphate, which is a precursor for nucleic acid synthesis.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520900', 520900, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'The main chemical component of genetic material in chromatin is', 'proteins', 'non-proteins', 'DNA', 'RNA', 'C', 'Genetic material in chromatin primarily consists of DNA, which carries the hereditary information.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520906', 520906, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which factor is involved in maintaining the fidelity of DNA replication?', 'anticodon''s degeneracy', 'SOS repair mechanism of DNA', 'nuclease activity of DNA polymerase', 'high specificity of aminoacyl-tRNA synthetase', 'C', 'Nuclease activity of DNA polymerase helps in proofreading and removing incorrect nucleotides during replication, thus maintaining the fidelity of DNA replication.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520924', 520924, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which of the following is incorrect about DNA replication in eukaryotes?', 'RNA primers are shorter', 'Okazaki fragments are longer', 'Multiple replication origins', 'Bidirectional replication, forming replication forks', 'B', 'In eukaryotes, Okazaki fragments are indeed longer compared to prokaryotes due to the larger size of their DNA molecules and the presence of multiple replication origins.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520926', 520926, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which of the following statements about telomerase is incorrect?', 'is an RNA-protein complex', 'contains an RNA template', 'has reverse transcriptase activity', 'catalyzes the extension of the template strand DNA', 'D', 'Telomerase has reverse transcriptase activity and functions to extend the telomere sequence on the DNA, not directly catalyze the extension of the template strand DNA.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520941', 520941, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which component is part of telomerase?', 'DNA polymerase + substrate', 'reverse transcriptase + RNA', 'RNA polymerase + co-factor', 'DNA repair enzyme + primer', 'B', 'Telomerase consists of reverse transcriptase and RNA.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520950', 520950, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Thymine dimers interfere with DNA synthesis by', 'causing a break in the DNA template strand', 'forming apurinic/apyrimidic sites in DNA strands', 'causing bends and kinks, affecting the DNA double helix, thereby hindering replication and transcription', 'forming negative supercoils between the two DNA strands', 'C', 'Thymine dimers cause structural distortions in the DNA molecule by creating bends and kinks. These distortions interfere with the normal processes of DNA replication and transcription, making option C the correct answer.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520996', 520996, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Protein synthesis occurs in the', 'nucleosome', 'mitochondria', 'ribosomes', 'nucleus', 'C', 'Protein synthesis primarily takes place on ribosomes. Nucleosomes are structures within chromosomes, mitochondria are involved in energy production, and the nucleus houses DNA but does not directly synthesize proteins.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-521061', 521061, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'In prokaryotes, several enzymes related to a particular metabolic pathway are often coordinately expressed through which mechanism?', 'transcription factor', 'operon', 'enhancer', 'attenuator', 'B', 'Coordinately expressed enzymes in prokaryotes are typically regulated by an operon, where a single promoter controls the transcription of multiple structural genes.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-521063', 521063, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which of the following statements about operons is correct?', 'Several structural genes in series are controlled by one promoter', 'Each of several structural genes in series has a different promoter', 'A single structural gene has multiple promoters', 'Transcription produces monocistronic RNA', 'A', 'In operons, several structural genes are transcribed together under the control of one promoter.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-521076', 521076, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'In the lac operon model of E. coli, what binds to the operator sequence to regulate transcription?', 'repressor protein', 'RNA polymerase', 'regulatory gene', 'cAMP-CAP', 'A', 'The repressor protein binds to the operator sequence in the lac operon of E. coli to regulate transcription.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-521095', 521095, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'In E. coli, the function of the SD sequence in the efficient expression of an exogenous gene is to provide', 'a mRNA transcription terminator', 'a ribosome binding site', 'a translation termination site', 'a selective splicing site', 'B', 'The SD sequence provides a ribosome binding site, which enhances the efficiency of protein synthesis by facilitating the initiation of translation.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-521139', 521139, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which of the following is not an extracellular signal molecule received by intracellular receptors?', 'steroid hormones', 'nitric oxide', 'thyroxine', 'insulin', 'D', 'Insulin acts through cell surface receptors and not intracellular receptors.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588344', 588344, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following cell organelles are present in both prokaryotic and eukaryotic cells?', 'cell wall', 'mitochondria', 'golgi apparatus', 'ribosomes', 'D', 'Ribosomes are found in both prokaryotic and eukaryotic cells. Cell walls, mitochondria, and golgi apparatus are typically present in eukaryotic cells but not necessarily in prokaryotic cells.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588348', 588348, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which of the following statements is incorrect about prokaryotic genetic material?', 'distributed in the cell nucleus', 'usually a circular DNA molecule', 'DNA is naked and does not combine with histones', 'controls cellular metabolism, growth, and reproduction', 'A', 'Prokaryotic cells do not have a distinct nucleus. The genetic material (DNA) is located in the cytoplasm. It can exist as circular DNA molecules and does not combine with histones. It controls cellular functions such as metabolism, growth, and reproduction.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588362', 588362, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which of the following statements is incorrect about eukaryotic cells?', 'Contain chromatin formed by multiple DNA molecules and histones', 'Transcription and translation of gene expression occur simultaneously', 'Have a complete nuclear structure', 'Are larger in size with diameters ranging from 10 to 100 μm', 'B', 'In eukaryotic cells, transcription and translation do not occur simultaneously; they are separated by a short interval due to the presence of nuclear membrane.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588742', 588742, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Where is the genetic material DNA found in animal cells?', 'only in the nucleus', 'only in the mitochondria', 'in the nucleus and mitochondria', 'in the nucleus and endoplasmic reticulum', 'C', 'DNA is primarily located in the nucleus of animal cells. However, a small amount of DNA is also found in mitochondria.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588795', 588795, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which of the following is synthesized directly from DNA as a template?', 'transcription factors', 'regulatory proteins', 'primase', 'hnRNA', 'D', 'hnRNA (heterogeneous nuclear RNA) is transcribed directly from DNA. Transcription factors, regulatory proteins, and primase are involved in the process but are not direct products of DNA replication.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588802', 588802, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Gene expression regulation cannot occur at the stage of', 'DNA replication', 'transcription initiation', 'post-transcriptional regulation', 'translation initiation', 'A', 'Gene expression regulation primarily occurs during transcription and translation. It does not directly involve DNA replication or post-translation modifications.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588809', 588809, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Transcription in eukaryotic cells occurs in the', 'nucleus', 'cytoplasm', 'mitochondria', 'endoplasmic reticulum', 'A', 'Transcription primarily takes place in the nucleus of eukaryotic cells.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588820', 588820, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Wobble in genetic code refers to', 'one anticodon can pair with several codons', 'a mechanism for extending peptide bonds in the ribosomal large subunit', 'the mechanism for forming peptide bonds during translation', 'the movement of ribosome along mRNA from its 5'' end to 3'' end', 'A', 'Wobble in genetic code refers to one anticodon can pair with several codons.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588825', 588825, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'At which level is gene expression regulated in the lactose operon model?', 'replication level', 'transcription level', 'post-transcriptional level', 'translation level', 'B', 'In the lactose operon model, gene expression is primarily regulated at the transcription level.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588830', 588830, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'In E. coli, the efficient expression of an exogenous gene is influenced by several factors. Among these, what role does the SD sequence play?', 'provides a mRNA transcription termination site', 'provides a ribosome binding site', 'provides a translation stop codon', 'provides a selective splicing site', 'B', 'The SD sequence provides a ribosome binding site, facilitating the initiation of protein synthesis during translation.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588848', 588848, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'DNA replication occurs in the', 'endoplasmic reticulum', 'golgi apparatus', 'ribosome', 'nucleus', 'D', 'DNA replication primarily takes place in the nucleus of eukaryotic cells.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-589004', 589004, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Calcium ions are stored within the', 'endoplasmic reticulum', 'nucleus', 'cytoplasm', 'plasma membrane', 'A', 'The endoplasmic reticulum is involved in storing calcium ions, which are crucial for various cellular processes.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-589104', 589104, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Gene expression regulation during cell differentiation mainly occurs at the level of', 'translation', 'post-translation', 'DNA replication', 'transcription', 'D', 'During cell differentiation, gene expression is primarily regulated at the transcriptional level. This involves the initiation and regulation of RNA synthesis from DNA templates.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-589135', 589135, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'In non-selective autophagy, the area where proteins or organelles are randomly transported and degraded is', 'lysosome', 'mitochondria', 'cytoplasm', 'peroxisome', 'A', 'Lysosomes are responsible for degrading proteins and organelles in non-selective autophagy. Mitochondria, cytoplasm, and peroxisomes do not primarily function in the degradation of random proteins or organelles.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-589160', 589160, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following is formed by lysosomes and contains insoluble lipoprotein particles?', 'nucleolus', 'cell nucleus', 'chromosomes', 'lipofuscin', 'D', 'Lipofuscin, also known as residual bodies, is formed by lysosomes and contains insoluble lipoprotein particles.', 100, 95, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588773', 588773, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following cellular structures has enzymes similar to those found in the nuclear membrane?', 'mitochondria', 'Golgi apparatus', 'endoplasmic reticulum', 'lysosomes', 'C', 'The nuclear envelope contains enzymes involved in lipid synthesis and other metabolic processes, which are also found in the endoplasmic reticulum.', 100, 92, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-589163', 589163, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following is not a change observed in cell aging?', 'cell nucleus enlargement', 'endoplasmic reticulum becomes diffuse', 'mitochondria number decreases', 'mitochondria volume decreases', 'A', 'Cell nucleus enlargement is not typically associated with the changes observed in cell aging. Other options are correct as they represent typical changes seen during cellular senescence.', 100, 92, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516300', 516300, 'NEET-UG', 'Biology', 'excretion-and-kidney-function', 'excretion-and-kidney-function', 'NCERT Biology Class 11, Chapter 16', 'The function of the juxtaglomerular apparatus in the kidney is to', 'synthesize angiotensinogen', 'secrete renin', 'control phosphate excretion', 'regulate water reabsorption by the collecting duct', 'B', 'The juxtaglomerular apparatus in the kidney secretes renin, which is part of the renin-angiotensin system and plays a crucial role in regulating blood pressure.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516430', 516430, 'NEET-UG', 'Biology', 'neuron-nerve-impulse-synapse', 'neuron-nerve-impulse-synapse', 'NCERT Biology Class 11, Chapter 18', 'When a postsynaptic neuron is excited, the action potential generally first erupts in the axon hillock mainly due to', 'the summation of EPSP here reaches its maximum', 'high density expression of voltage-gated sodium channels in the hillock', 'lowest resting membrane potential here', 'lack of potassium channels here', 'B', 'Voltage-gated sodium channels are highly concentrated in the axon hillock, facilitating the rapid initiation and propagation of action potentials.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516615', 516615, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which hormone is not regulated by the adenohypophysis?', 'glucocorticoids', 'thyroid hormones', 'parathyroid hormone', 'estrogens', 'C', 'Parathyroid hormone is directly controlled by the parathyroid gland and not regulated by the adenohypophysis.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516616', 516616, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which of the following is not related to ACTH secretion regulation?', 'action of hypothalamic corticotropin-releasing hormone', 'feedback regulation by glucocorticoids', 'feedback regulation by aldosterone', 'regulation by hypothalamo-pituitary-adrenal axis', 'C', 'ACTH secretion is regulated by the hypothalamic corticotropin-releasing hormone and feedback mechanisms involving glucocorticoids. The regulation also involves the hypothalamo-pituitary-adrenal axis, but aldosterone does not directly regulate ACTH secretion.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516625', 516625, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which of the following is the location where melatonin is synthesized and secreted?', 'thyroid gland', 'pancreatic islets', 'pineal body', 'adrenal medulla', 'C', 'Melatonin is produced by the pineal body in the brain. It regulates sleep-wake cycles and other physiological processes.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516658', 516658, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which of the following hormones can pass through the cell membrane and bind to nuclear receptors to exert its effect?', 'growth hormone', 'insulin', 'thyroid hormone', 'adrenaline', 'C', 'Thyroid hormones are lipid-soluble and can pass through the cell membrane, entering the cell where they bind to nuclear receptors to exert their effects. Other options do not have this characteristic.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516661', 516661, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which hormone is crucial for brain development in fetuses and newborns?', 'growth hormone', 'thyroid hormone', 'insulin', 'adrenaline', 'B', 'Thyroid hormone is crucial for brain development in fetuses and newborns. During embryonic development, it promotes neuronal proliferation, differentiation, axon formation, and synaptic development, as well as the growth of glial cells and myelination, which are important for the maturation of bone-formation centers during infancy.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516698', 516698, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which one belongs to the tyrosine kinase receptor?', 'adrenal cortex hormone receptor', 'thyroid-stimulating hormone receptor', 'follicle-stimulating hormone receptor', 'insulin receptor', 'D', 'Insulin receptors are a type of tyrosine kinase receptors involved in the signaling pathway for insulin.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516716', 516716, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which of the following is incorrect about adrenocorticotropic hormone (ACTH) secretion?', 'regulated by corticotropin-releasing hormone from the hypothalamus', 'under negative feedback regulation by glucocorticoids', 'under negative feedback regulation by aldosterone', 'increases during stress', 'C', 'ACTH secretion is regulated by corticotropin-releasing hormone (CRH) from the hypothalamus and is under negative feedback regulation by glucocorticoids, but not by aldosterone. ACTH also increases during stress.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520545', 520545, 'NEET-UG', 'Biology', 'plant-respiration', 'plant-respiration', 'NCERT Biology Class 11, Chapter 12', 'The tricarboxylic acid cycle is considered an aerobic metabolic pathway because', 'it requires oxygen for certain reactions', 'CO2 is a product of the cycle', 'reducing equivalents need to be oxidized through the electron transport chain', 'substrate-level phosphorylation occurs', 'A', 'The tricarboxylic acid (TCA) cycle, also known as the citric acid cycle or Krebs cycle, is considered an aerobic metabolic pathway because certain reactions within it require oxygen. While CO2 and substrate-level phosphorylation are products of the TCA cycle, they do not directly indicate its dependence on oxygen. The reducing equivalents generated in the cycle must be oxidized through the electron transport chain to produce ATP.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520555', 520555, 'NEET-UG', 'Biology', 'plant-respiration', 'plant-respiration', 'NCERT Biology Class 11, Chapter 12', 'In the following reactions, which step of the citric acid cycle and oxidative phosphorylation produces the most ATP?', 'Fumarate → Malate', 'Succinate → Fumarate', 'α-Ketoglutarate → Succinate', 'Isocitrate → α-Ketoglutarate', 'C', 'The step of the citric acid cycle where the most ATP is produced through oxidative phosphorylation is from α-ketoglutarate to succinate. This reaction involves the reduction of FAD and NAD+, which are later used in the electron transport chain to generate ATP.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520570', 520570, 'NEET-UG', 'Biology', 'plant-respiration', 'plant-respiration', 'NCERT Biology Class 11, Chapter 12', 'Which of the following metabolic processes does not take place in the mitochondria?', 'glycolysis', 'citric acid cycle', 'beta-oxidation of fatty acids', 'electron transport chain', 'A', 'Glycolysis occurs in the cytoplasm, while the other processes take place in the mitochondria.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520571', 520571, 'NEET-UG', 'Biology', 'plant-respiration', 'plant-respiration', 'NCERT Biology Class 11, Chapter 12', 'The main way of ATP production in the body is', 'oxidative phosphorylation', 'substrate-level phosphorylation', 'citric acid cycle', 'phosphocreatine breakdown', 'A', 'Oxidative phosphorylation is the primary method of ATP production in most cells. Substrate-level phosphorylation occurs directly within metabolic pathways, while the citric acid cycle generates intermediates used for energy but not ATP directly. Phosphocreatine breakdown provides a rapid source of phosphate groups but is not the main way of ATP production.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520843', 520843, 'NEET-UG', 'Biology', 'plant-respiration', 'plant-respiration', 'NCERT Biology Class 11, Chapter 12', 'Which metabolic reaction cannot occur in the mitochondria?', 'glycolysis', 'ketone body formation', 'citric acid cycle', 'oxidative phosphorylation', 'A', 'Glycolysis takes place in the cytoplasm, not in the mitochondria. Ketone body formation, citric acid cycle (Krebs cycle), and oxidative phosphorylation are all mitochondrial processes.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520897', 520897, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'In eukaryotic organisms, the main location of the genome is in', 'plasmid', 'mitochondrion', 'ribosome', 'nucleus', 'D', 'The genome of eukaryotic organisms primarily resides within the nucleus. Plasmids, mitochondria, and ribosomes have other functions in the cell.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-521093', 521093, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which of the following is correct regarding the regulation of tryptophan operon?', 'Only primer RNA is synthesized when tryptophan is present', 'Transcription is terminated prematurely when tryptophan is absent', 'It involves translational control', 'It has an anti-termination function', 'B', 'The regulation of the tryptophan operon occurs at the transcriptional level. Tryptophan acts as a repressor, binding to the repressor protein which then binds to the operator region preventing transcription. When tryptophan levels are low, the repressor is less effective, allowing transcription to proceed.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-521273', 521273, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'What is the main role of iodine in the body?', 'participates in adrenaline composition', 'participates in thyroid hormone composition', 'participates in TSH composition', 'participates in glucocorticoid composition', 'B', 'Iodine is essential for the synthesis of thyroid hormones, which regulate metabolism and growth.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-521384', 521384, 'NEET-UG', 'Biology', 'recombinant-dna-technology', 'recombinant-dna-technology', 'NCERT Biology Class 12, Chapter 9', 'Which of the following techniques involves the use of restriction enzymes?', 'Quantitative PCR', 'ASO', 'RFLP', 'SSCP', 'C', 'Restriction Fragment Length Polymorphism (RFLP) is a molecular biology technique that uses restriction enzymes to cut DNA at specific recognition sites, creating fragments of varying lengths. These fragments are then separated by gel electrophoresis and visualized using radioactive or fluorescent probes.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-579017', 579017, 'NEET-UG', 'Biology', 'mutation-and-gene-expression', 'mutation-and-gene-expression', 'NCERT Biology Class 12, Chapter 5', 'Due to a mutation that changes a coding codon into a termination codon, such a mutation is known as', 'missense mutation', 'nonsense mutation', 'termination codon mutation', 'frameshift mutation', 'B', 'A nonsense mutation results in the premature termination of protein synthesis due to a change in a coding codon into a termination codon.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-579035', 579035, 'NEET-UG', 'Biology', 'mutation-and-gene-expression', 'mutation-and-gene-expression', 'NCERT Biology Class 12, Chapter 5', 'Which of the following is not a term used to describe mutations in structural genes?', 'misplacement mutation', 'point mutation', 'nonsense mutation', 'termination codon mutation', 'A', 'Misplacement mutation is not a standard term used for describing mutations in structural genes. Point mutation, nonsense mutation, and termination codon mutation are recognized terms.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-579057', 579057, 'NEET-UG', 'Biology', 'mutation-and-gene-expression', 'mutation-and-gene-expression', 'NCERT Biology Class 12, Chapter 5', 'Huntington gene''s first exon shows (CAG)n repeats, with less than 35 repeats considered normal and more than 35 leading to Huntington disease. This mechanism of disease caused by the change in (CAG)n repeat number is known as', 'missense mutation', 'nonsense mutation', 'frameshift mutation', 'dynamic mutation', 'D', 'Dynamic mutations refer to changes in the number of repeats, such as (CAG)n, leading to genetic disorders like Huntington disease.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-579069', 579069, 'NEET-UG', 'Biology', 'pedigree-analysis-and-inheritance-patterns', 'pedigree-analysis-and-inheritance-patterns', 'NCERT Biology Class 12, Chapter 4', 'Consanguineous marriage can significantly increase the incidence of which type of genetic disorder?', 'autosomal dominant inheritance', 'autosomal recessive inheritance', 'X-linked dominant inheritance', 'X-linked recessive inheritance', 'B', 'Autosomal recessive inheritance is more likely to show an increased incidence due to consanguineous marriage as it requires two copies of the recessive allele, which are more common in closely related individuals.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-579101', 579101, 'NEET-UG', 'Biology', 'pedigree-analysis-and-inheritance-patterns', 'pedigree-analysis-and-inheritance-patterns', 'NCERT Biology Class 12, Chapter 4', 'Consanguineous marriage can most significantly increase the risk of which type of disease?', 'autosomal dominant inheritance', 'autosomal recessive inheritance', 'X-linked dominant inheritance', 'X-linked recessive inheritance', 'B', 'Autosomal recessive inheritance is more likely to be expressed in offspring when both parents are carriers, which is more common in consanguineous marriages.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-579532', 579532, 'NEET-UG', 'Biology', 'pedigree-analysis-and-inheritance-patterns', 'pedigree-analysis-and-inheritance-patterns', 'NCERT Biology Class 12, Chapter 4', 'The mode of inheritance for Duchenne muscular dystrophy is', 'AR', 'XR', 'XD', 'Y-linked', 'C', 'Duchenne muscular dystrophy is an X-linked recessive disorder.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-579543', 579543, 'NEET-UG', 'Biology', 'pedigree-analysis-and-inheritance-patterns', 'pedigree-analysis-and-inheritance-patterns', 'NCERT Biology Class 12, Chapter 4', 'The inheritance pattern of Gaucher disease is', 'autosomal dominant', 'autosomal recessive', 'X-linked dominant', 'X-linked recessive', 'B', 'Gaucher disease follows an autosomal recessive inheritance pattern.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-579546', 579546, 'NEET-UG', 'Biology', 'pedigree-analysis-and-inheritance-patterns', 'pedigree-analysis-and-inheritance-patterns', 'NCERT Biology Class 12, Chapter 4', 'Most inherited metabolic defects are mostly due to', 'autosomal dominant inheritance', 'autosomal recessive inheritance', 'X-linked dominant inheritance', 'X-linked recessive inheritance', 'B', 'Inherited metabolic defects are more commonly associated with autosomal recessive inheritance. Autosomal dominant, X-linked dominant, and X-linked recessive patterns are less frequent for such conditions.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-579957', 579957, 'NEET-UG', 'Biology', 'pedigree-analysis-and-inheritance-patterns', 'pedigree-analysis-and-inheritance-patterns', 'NCERT Biology Class 12, Chapter 4', 'In pedigree analysis, a male patient with a genetic disease has parents and grandparents who are normal, one uncle is also normal, but the other uncle suffers from the same disease. Determine the mode of inheritance for this genetic disease.', 'autosomal dominant', 'autosomal recessive', 'X-linked dominant', 'X-linked recessive', 'B', 'The presence of the disease in one uncle and not in the other suggests that the affected gene is on an autosome. The fact that both parents are normal but their son has the disease indicates that it is a recessive trait.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588339', 588339, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'The basic structural and functional unit of life in the human body is', 'cell membrane', 'nucleus', 'ribosome', 'cell', 'D', 'Cell theory states that cells are the fundamental units of structure and function in living organisms. Among the given options, only ''cell'' fits this description.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588535', 588535, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following cell organelles is associated with the outer nuclear membrane?', 'endoplasmic reticulum', 'golgi apparatus', 'lysosomes', 'mitochondria', 'A', 'The endoplasmic reticulum (ER) has a continuous connection with the nuclear envelope, including both the outer and inner nuclear membranes. The other organelles listed do not have direct connections with the outer nuclear membrane.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588536', 588536, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following cell organelles is involved in Ca^2+ uptake and release, as well as the conduction of excitation in muscle cells?', 'microtubules and microfilaments', 'lysosomes', 'rough endoplasmic reticulum', 'smooth endoplasmic reticulum', 'D', 'Smooth endoplasmic reticulum (SER) is involved in Ca^2+ storage and release, which plays a crucial role in muscle cell excitation-contraction coupling.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588548', 588548, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following cell organelles is enclosed by a double membrane in cells?', 'endoplasmic reticulum', 'mitochondria', 'lysosome', 'golgi apparatus', 'B', 'Mitochondria are the only organelle that is always enclosed by a double membrane in cells.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588556', 588556, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following cell organelles have proton pumps in their membrane?', 'peroxisomes', 'endoplasmic reticulum', 'lysosomes', 'golgi apparatus', 'C', 'Lysosomes contain proton pumps which help in the hydrolysis of substances within them.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588558', 588558, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following cell organelles has polarity?', 'mitochondria', 'endoplasmic reticulum', 'lysosomes', 'golgi apparatus', 'D', 'Golgi apparatus has a polarized structure with cis and trans faces, making it the only cell organelle listed that exhibits polarity.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588573', 588573, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following membranous organelles is not part of the endomembrane system?', 'endoplasmic reticulum', 'lysosomes', 'transport vesicles', 'mitochondria', 'D', 'The endomembrane system includes organelles such as the endoplasmic reticulum, lysosomes, and transport vesicles. Mitochondria are not part of this system.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588601', 588601, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'The main site for biological oxidation and energy conversion in cells is', 'ribosome', 'rough endoplasmic reticulum', 'mitochondrion', 'peroxisome', 'C', 'Mitochondria are known as the powerhouses of the cell, where most of the ATP (adenosine triphosphate) is generated through cellular respiration.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588609', 588609, 'NEET-UG', 'Biology', 'plant-respiration', 'plant-respiration', 'NCERT Biology Class 11, Chapter 12', 'The process of glucose breakdown to produce ATP is', 'glycolysis → pyruvate oxidation → citric acid cycle → electron transport and oxidative phosphorylation', 'glycolysis → electron transport and oxidative phosphorylation → pyruvate oxidation → citric acid cycle', 'pyruvate oxidation → citric acid cycle → glycolysis → electron transport and oxidative phosphorylation', 'pyruvate oxidation → citric acid cycle → electron transport and oxidative phosphorylation → glycolysis', 'A', 'The correct sequence is glycolysis, followed by pyruvate oxidation, then the citric acid cycle, and finally electron transport and oxidative phosphorylation.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-589057', 589057, 'NEET-UG', 'Biology', 'human-reproductive-system-and-gametogenesis', 'human-reproductive-system-and-gametogenesis', 'NCERT Biology Class 12, Chapter 2', 'The determinant of gender is', 'mature division in spermatogenesis', 'mature division in oogenesis', 'chromosome pattern in the egg at fertilization', 'chromosome pattern in the sperm at fertilization', 'D', 'The determinant of gender is determined by the chromosome pattern in the sperm at fertilization, as it determines whether the zygote receives an X or Y chromosome.', 100, 90, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516588', 516588, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which of the following is a lipid hormone?', 'aldosterone', 'insulin', 'thyroid-stimulating hormone', 'adrenocorticotropic hormone', 'A', 'Aldosterone is a steroid hormone, which belongs to the class of lipid hormones. Insulin, thyroid-stimulating hormone, and adrenocorticotropic hormone are peptide or protein hormones.', 100, 85, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-516628', 516628, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which endocrine gland is most sensitive to melatonin inhibition?', 'pituitary', 'thyroid', 'pancreas', 'adrenal', 'A', 'Melatonin primarily inhibits the pituitary gland, particularly the release of gonadotropins.', 100, 85, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-520587', 520587, 'NEET-UG', 'Biology', 'endocrine-system-and-hormones', 'endocrine-system-and-hormones', 'NCERT Biology Class 11, Chapter 19', 'Which hormone can regulate oxidative phosphorylation?', 'thyroxine', 'adrenaline', 'corticosteroids', 'insulin', 'A', 'Thyroxine, a hormone produced by the thyroid gland, plays a crucial role in regulating metabolic processes including oxidative phosphorylation. Adrenaline, corticosteroids, and insulin do not directly regulate this process.', 100, 85, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-521092', 521092, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'Which of the following is an incorrect description about the tryptophan operon?', 'Ribosomes are involved in transcription termination', 'Transcription and translation coupling forms its molecular basis for transcription regulation', 'Tryptophan deficiency leads to premature transcription termination', 'Attenuator is a key regulatory element', 'A', 'The tryptophan operon''s regulation involves the attenuation process, not ribosomal involvement in transcription termination. Transcription and translation coupling are indeed part of its regulatory mechanism. Tryptophan deficiency leads to premature transcriptional termination through attenuation. The attenuator is a key component.', 100, 85, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-521391', 521391, 'NEET-UG', 'Biology', 'mutation-and-gene-expression', 'mutation-and-gene-expression', 'NCERT Biology Class 12, Chapter 5', 'Which mechanism generally causes only a change in gene expression levels?', 'frameshift mutation', 'missense mutation', 'nonsense mutation', 'haploinsufficiency', 'D', 'Haploinsufficiency refers to the condition where a reduction in the number of copies of a gene results in a decrease in the level of gene expression, leading to a loss of function. This mechanism generally causes only a change in gene expression levels.', 100, 85, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-578586', 578586, 'NEET-UG', 'Biology', 'basic-genetic-diseases-as-inheritance-examples', 'basic-genetic-diseases-as-inheritance-examples', 'NCERT Biology Class 12, Chapter 7', 'Which single-gene disorder can be induced by environmental factors?', 'Huntington''s disease', 'G6PD deficiency (also known as favism)', 'Albinism', 'Haemophilia A', 'B', 'G6PD deficiency, also known as favism, can be triggered by certain environmental factors such as fava beans or specific medications. The other options are not typically influenced by environmental triggers.', 100, 85, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-579914', 579914, 'NEET-UG', 'Biology', 'dna-rna-replication-transcription-translation', 'dna-rna-replication-transcription-translation', 'NCERT Biology Class 12, Chapter 5', 'The basic principle of nucleic acid hybridization is', 'denaturation and renaturation', 'DNA replication', 'transcription', 'translation', 'A', 'Nucleic acid hybridization involves the process of denaturation, where the double-stranded DNA or RNA is separated into single strands, followed by renaturation when complementary strands reassociate under suitable conditions.', 100, 85, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588084', 588084, 'NEET-UG', 'Biology', 'immunity-pathogens-vaccines', 'immunity-pathogens-vaccines', 'NCERT Biology Class 12, Chapter 7', 'The main defense against fungal infections in the body depends on', 'cellular immunity', 'humoral immunity', 'innate immunity', 'acquired immunity', 'C', 'Fungal infections are primarily dealt with by the innate immune system, which includes physical and chemical barriers as well as non-specific cellular responses.', 100, 85, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588346', 588346, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following cell organelles enables eukaryotic cells to survive in an oxygen-rich environment on Earth?', 'Golgi apparatus', 'Mitochondria', 'Lysosomes', 'Endoplasmic reticulum', 'B', 'Mitochondria are the powerhouses of the cell, producing energy through cellular respiration. This process is crucial for eukaryotic cells to survive in an oxygen-rich environment.', 100, 85, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO questions (id, source_id, exam, subject, topic_id, topic_slug, ncert_ref, stem, option_a, option_b, option_c, option_d, correct_option, explanation, quality_score, qwenmax_review_score, status, is_free)
VALUES ('neetug-bio-588615', 588615, 'NEET-UG', 'Biology', 'cell-theory-and-cell-organelles', 'cell-theory-and-cell-organelles', 'NCERT Biology Class 11, Chapter 8', 'Which of the following cell organelles contains the highest amount of enzymes?', 'mitochondria', 'endoplasmic reticulum', 'golgi apparatus', 'peroxisomes', 'A', 'Mitochondria are known for their high enzyme content, which is essential for cellular respiration and energy production.', 100, 85, 'approved', true)
ON CONFLICT (source_id) DO UPDATE SET stem = EXCLUDED.stem, explanation = EXCLUDED.explanation, updated_at = now();

INSERT INTO seo_pages (id, type, slug, title, description, target_keyword, topic_slug, status)
VALUES ('note-endocrine-system-and-hormones', 'topic_note', 'endocrine-system-and-hormones', 'Endocrine system and hormones: NEET-UG Biology NCERT Revision Notes', 'Revise Endocrine system and hormones for NEET-UG Biology with NCERT-aligned concepts, MCQ practice, and answer explanations.', 'Endocrine system and hormones NEET UG Biology questions', 'endocrine-system-and-hormones', 'published')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, updated_at = now();

INSERT INTO seo_pages (id, type, slug, title, description, target_keyword, topic_slug, status)
VALUES ('note-dna-rna-replication-transcription-translation', 'topic_note', 'dna-rna-replication-transcription-translation', 'DNA RNA replication transcription translation: NEET-UG Biology NCERT Revision Notes', 'Revise DNA RNA replication transcription translation for NEET-UG Biology with NCERT-aligned concepts, MCQ practice, and answer explanations.', 'DNA RNA replication transcription translation NEET UG Biology questions', 'dna-rna-replication-transcription-translation', 'published')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, updated_at = now();

INSERT INTO seo_pages (id, type, slug, title, description, target_keyword, topic_slug, status)
VALUES ('note-cell-theory-and-cell-organelles', 'topic_note', 'cell-theory-and-cell-organelles', 'Cell theory and cell organelles: NEET-UG Biology NCERT Revision Notes', 'Revise Cell theory and cell organelles for NEET-UG Biology with NCERT-aligned concepts, MCQ practice, and answer explanations.', 'Cell theory and cell organelles NEET UG Biology questions', 'cell-theory-and-cell-organelles', 'published')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, updated_at = now();

INSERT INTO seo_pages (id, type, slug, title, description, target_keyword, topic_slug, status)
VALUES ('note-plant-respiration', 'topic_note', 'plant-respiration', 'Plant respiration: NEET-UG Biology NCERT Revision Notes', 'Revise Plant respiration for NEET-UG Biology with NCERT-aligned concepts, MCQ practice, and answer explanations.', 'Plant respiration NEET UG Biology questions', 'plant-respiration', 'published')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, updated_at = now();

INSERT INTO seo_pages (id, type, slug, title, description, target_keyword, topic_slug, status)
VALUES ('note-pedigree-analysis-and-inheritance-patterns', 'topic_note', 'pedigree-analysis-and-inheritance-patterns', 'Pedigree analysis and inheritance patterns: NEET-UG Biology NCERT Revision Notes', 'Revise Pedigree analysis and inheritance patterns for NEET-UG Biology with NCERT-aligned concepts, MCQ practice, and answer explanations.', 'Pedigree analysis and inheritance patterns NEET UG Biology questions', 'pedigree-analysis-and-inheritance-patterns', 'published')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, updated_at = now();
